### ISSUE TITLE
Video Skipping in European Exclusive Bullfrog Games (Syndicate + Theme Park)

### ISSUE THREAD

**Issue by 630216-29-2400** [MiSTer-devel/MegaCD_MiSTer#47] opened 2020-06-20 19:05 UTC
Having identical issues with both European exclusive releases from Bullfrog. 
Starting either **Syndicate** or **Theme Park** with an EU BIOS and region causes the attract videos to pause approximately every three seconds or so while playing.
The audio plays correctly in both games while doing this.
To double check I started both up with US BIOS and Region and the same for JP BIOS and Region. This shows the same issues with the atract videos but also corrupts the audio playback as this now skips too due to the increased speed.
The only other European exclusive release that I'm aware of is **Sensible Soccer** which doesn't skip at all with EU BIOS and settings but does understandably play back too quickly with either US or JP settings so it appears to possibly be an issue with the two Bullfrog releases only. Maybe the same issue?

**Comment by MAME-GETTER** [comment] 2021-01-06 17:17
I can confirm this same skipping with Syndicate.

Results are the same with both CIFS and SDCARD and CHD compressed and uncompressed.

**Comment by pa-august** [comment] 2022-06-26 15:47
Are we certain the games behaved differently on original hardware? Searching on youtube I can find no instances of the mega cd version of the intro running _without_ the pausing.

**Comment by birdybro** [comment] 2022-06-26 19:44
https://www.youtube.com/watch?v=E78GWV680-U - Confirmed this occurs on original hardware. It's not a bug in the core. This issue can probably be closed as a result.

**Closed** 2022-06-26 22:03 UTC
